### ISSUE TITLE
requestBody should not merge examples for error 

### ISSUE THREAD

**Issue by blocknotes** [exoego/rspec-openapi#140]
Hey 😄 
We are having some issues on a project where we have multiple tests for the same endpoint.

I prepared a PR to expose the situation: https://github.com/exoego/rspec-openapi/pull/139

Some notes:
- the changes to _spec/rails/app/controllers/tables_controller.rb_ simulate a validation error;
- the test 'fails to create a table' covers a situation where a required parameter is missing;
- the test 'fails to create a table (2)' covers a situation where a required parameter has an invalid value.

My points/doubts about the outcome:
- in the create schema request, in the example, the name value gets overridden: `name: k0kubun` => `name: some_invalid_name` - so a value from the test 'fails to create a table' is mixed with 'returns a table' test;
- `name` is not a required parameter anymore.

Is this behaviour expected?

I also tried using `openapi: false` to exclude specific tests but I think that it's not always possible to avoid the merging, especially if you want to document both good & bad paths (/status codes).

**Comment by exoego** [comment]
Relates to https://github.com/exoego/rspec-openapi/issues/138

> Is this behaviour expected?

Right now, yes.
The current implementation assumes that responses from the same API share the same JSON structure.
So rspec-openapi collects API responses and merges.
I do not remember the details, but a response from the last test case overwrites the former ones.

I understand this assumption is only sometimes valid.
Also, the order of test cases matters, which could be more intuitive.

We may group responses by same HTTP status code and merge in each group.

**Comment by exoego** [comment]
I've checked source code and updated the title.
