### ISSUE TITLE
Regenerating (remove file and run rspec) the schema without changing the code, generates different file.

### ISSUE THREAD

**Issue by ipepe** [exoego/rspec-openapi#159]
Regenerating (remove file and run rspec) the schema without changing the code, generates different file. I assume this is because RSpec is executing tests in different order each time and this causes schema to be generated differently. Would be nice to have some counter-measures for this like:
 - http status code keys are ordered in ascending manner
   - this should prevent code 400 and 500 to be in different order each time based on rspec randomization of order of tests
 - any schema keys are ordered alphabetically
   - this should prevent situations where payload is being extended by one or other test

**Comment by exoego** [comment]
This makes sense.
Keys should be ordered lexicographically.
#155 implemented `paths` ordering, which should be generalized to other properties.
