### ISSUE TITLE
If parameter has symbol, it will be error

### ISSUE THREAD

**Issue by lion-man44** [exoego/rspec-openapi#219]
I just update this gem v0.18.0 and got error like this.

```rb
     Failure/Error: Integer(string || '')

     TypeError:
       can't convert Symbol into Integer
```

I found problem here.
This code can't get Symbol.
```rb
  def number_or_nil(string)
    Integer(string || '')
  rescue ArgumentError
    nil
  end
```

if you use `json` in router or something, probably it includes Symbol in value this code.
```rb
    parameters.each_pair do |key, value|
      next unless number_or_nil(value)
```

This is my parameters.
```rb
{:format=>:json, :controller=>"*", :action=>"create", :id=>"897"}
```

So, could anyone help to submit PR like this?
```rb
      next unless number_or_nil(value.to_s)
```

I tried to create PR but I couldn't understand how to write test code in this gem.

**Comment by exoego** [comment]
Could you make a repro, something like this:
https://github.com/rhiroe/try-rspec-openapi

**Comment by lion-man44** [comment]
Sorry, it will take times in my environment if you are okay just try this one in your router.

```
Rails.application.routes.draw do
  defaults format: :json do
  end
end
```

And then, I found workaround thankfully if I rewrite `:json` to `'json'` as a String.
It works

```
Rails.application.routes.draw do
  defaults format: 'json' do
  end
end
```

**Comment by johnphamvan** [comment]
Thanks for the workaround @lion-man44.

A bit more info for @exoego, while running the gem locally with a bit of debug code:
```
    76:   def number_or_nil(string)
    77:     if string.is_a?(String)
    78:       Integer(string || '')
    79:     else
 => 80:       binding.irb
    81:     end
    82:   rescue ArgumentError
    83:     nil
    84:   end
    85: end

irb(#<Object:0x000000013c835990>):001> string
=> :json
```

**Comment by exoego** [comment]
@lion-man44 @johnphamvan 
Thanks for reporting. This was fixed and released in v0.18.1

**Comment by johnphamvan** [comment]
Thanks for maintaining this project @exoego!

**Comment by lion-man44** [comment]
Thanks for fixing this @exoego 
And Thanks for helping me @johnphamvan
