### ISSUE TITLE
hanami: non-integer path variable is not supported

### ISSUE THREAD

**Issue by exoego** [exoego/rspec-openapi#227]
While I was working in #226, I noticed that Hanami support is broken.
It can not handle non-numeric path variable like `/sites/{name}` where `name` can be `foo` or `bar`.

I think it is an upstream issue in Hanami side, and reported in Hanami router: https://github.com/hanami/router/issues/271

**Comment by AlexeyMatskevich** [comment]
Confirming the problem

**Comment by exoego** [comment]
Closed by https://github.com/exoego/rspec-openapi/pull/231
