### ISSUE TITLE
Can we support 'required' ?

### ISSUE THREAD

**Issue by hotanlam** [exoego/rspec-openapi#89]
Can we support 'required' ? Like this 

```
requestBody:
  content:
    application/x-www-form-urlencoded:
      encoding: {}
      schema:
        required:
          - name
```

**Comment by exoego** [comment]
No.
`required` is generated only for path parameter at this moment.
It will be a great enhancement if rspec-openapi supports `required` in other places.

**Comment by chrishough** [comment]
Bummer, JSON Schema supports this https://stackoverflow.com/questions/17931874/setting-required-on-a-json-schema-array
